-- AlterTable
ALTER TABLE "HIP" ADD COLUMN     "domainPoints" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "nftPoints" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "referralPoints" DOUBLE PRECISION NOT NULL DEFAULT 0;
